### ISSUE TITLE
Calories not transferred

### ISSUE THREAD

**Issue by leaderlessllc** [philosowaffle/peloton-to-garmin#414]
**Exercise transferred but calories show 0**

**To Reproduce**
1. Completed regular workout on Peloton
2. Allowed GitHub actions Cron job to sync.

**Expected behavior**
Am I wrong in the expectation or are calories indeed supposed to transfer?

**Comment by philosowaffle** [comment]
Interesting, yes it is expected for Calories to sync over to Garmin. I actually did a Peloton Core workout this evening and can see that my calories did sync as expected.  So might need more info to figure out what's different in your case.

On your Peloton app (or the website) does your Peloton workout display the Calories burned for your workout?

**Comment by leaderlessllc** [comment]
It does.. ![image](https://user-images.githubusercontent.com/110690954/211956941-1a3b60e9-1b4c-4ad7-b5b5-005340c9cabf.png)

**Comment by leaderlessllc** [comment]
An example of another workout calories ![image](https://user-images.githubusercontent.com/110690954/211958392-ba0c5ff2-606e-49e0-9802-ffabdce84745.jpeg)

**Comment by leaderlessllc** [comment]
![image](https://user-images.githubusercontent.com/110690954/211958782-3626e2c7-511f-4496-8d49-b353cc99819a.jpeg)

**Comment by leaderlessllc** [comment]
> Interesting, yes it is expected for Calories to sync over to Garmin. I actually did a Peloton Core workout this evening and can see that my calories did sync as expected.  So might need more info to figure out what's different in your case.
> 
> 
> 
> On your Peloton app (or the website) does your Peloton workout display the Calories burned for your workout?

Below I posted the examples, today agin same thing happened.. I tested the Docker based solution on my Mac and no difference..

**Comment by philosowaffle** [comment]
Could you send me a link to one of your Peloton workouts?  If your account is not public you'll either have to make that workout shareable or you can add me on Peloton (username: cyclesaurus).  Having a link to one of your example workouts should let me inspect the underlying peloton data and hopefully reveal why this is happening.

**Comment by leaderlessllc** [comment]
> Could you send me a link to one of your Peloton workouts?  If your account is not public you'll either have to make that workout shareable or you can add me on Peloton (username: cyclesaurus).  Having a link to one of your example workouts should let me inspect the underlying peloton data and hopefully reveal why this is happening.

I've added you

**Comment by philosowaffle** [comment]
This is fixed now in the `master` branch.  The root cause seems to be that when the Calories are provided to Peloton via Apple Watch, they are saved in a different field than normal, a field P2G didn't know to look at. I've updated P2G such that it will check both fields now to find Calories.

**Comment by mattaeus-isenberg** [comment]
Awesome thank you! 🙏

**Comment by mattaeus-isenberg** [comment]
I did a sync for the fork and tested it and issue persisted on GitHub actions.. is there a flag to change on the workflow? 

I deleted the activity and tested with the latest flag on Docker on Mac and it did sync with calories successfully.

**Comment by mattaeus-isenberg** [comment]
One more question... all activities that are synchronized show in CST, is there any way I can change it to PST to avoid duplicates?

**Comment by philosowaffle** [comment]
Yup, there are some examples on the [discussion forum](https://github.com/philosowaffle/peloton-to-garmin/discussions?discussions_q=timezone), you just have to modify the `TZ` environment variable to be your timezone instead of CST.
