### ISSUE TITLE
Garmin Upload - Authentication Error

### ISSUE THREAD

**Issue by jgramajo4** [philosowaffle/peloton-to-garmin#62]
Has anyone started encountering this issue recently? I have had this running without any issues for about 1.5 weeks and randomly overnight I started getting this issue below even though the password and everything is correct and I havent changed any settings.

`2021-01-06 03:23:47,402 [CRITICAL] Login Failure: Authentification failed.

Traceback (most recent call last):

  File "/opt/app/peloton-to-garmin.py", line 158, in <module>

    PelotonToGarmin.run(config)

  File "/opt/app/peloton-to-garmin.py", line 86, in run

    raise e

  File "/opt/app/peloton-to-garmin.py", line 83, in run

    garminUploader.uploadToGarmin(garminUploadHistoryTable)

  File "/opt/app/lib/garminClient.py", line 29, in uploadToGarmin

    assert self.user.authenticate(), "Failed to authenticate garmin user."

AssertionError: Failed to authenticate garmin user.`

**Comment by philosowaffle** [comment]
Hmmm, I am also seeing this error now. I fear Garmin may have closed off the "unofficial" authentication method this tool was using: https://github.com/La0/garmin-uploader

I'll have to see if the original author can either help find a fix, or see if I can figure it out myself.

**Comment by philosowaffle** [comment]
Logged an issue on the related library. If I have the time I will also try to see if I can find a fix and submit a pr.

https://github.com/La0/garmin-uploader/issues/20

**Comment by greenperro** [comment]
Hello,  I think this is the error I'm getting too, but the main window disappears too quickly for me to see the error.    The log file ends on "uploading...."

**Comment by philosowaffle** [comment]
Alright, this should be resolved now. 

If you use the zip `.exe` from the release page then just grab the latest release from [here](https://github.com/philosowaffle/peloton-to-garmin/releases).  

If you are using the master branch then fetch latest and re-run `pip install -r requirements.txt` to pick up the latest package version of the `garmin-uploader` library.

**Comment by amy26point2** [comment]
I use the master branch. After running the pip install -requirements.txt it said it uninstalled the old garmin-uploader and successfully installed garmin-uploader-1.0.8, however I'm still getting the same failed to authenticate garmin user error.

**Comment by philosowaffle** [comment]
I just re-tested this locally and upload seems to be working ok for me.

Do you mind double checking the version with:
```
pip show garmin-uploader
```

One other thing to check, verify when you fetched latest master branch that it did not overwrite your `config.ini` file back to default.

**Comment by amy26point2** [comment]
The uploader version is showing as 1.0.8. I did preserve my old config.ini file and manually checked that the password saved there has no issues with logging into the Garmin site. I also gave it the old cross your fingers and reboot, but no luck.

2021-01-07 08:25:48,520 - INFO - peloton-to-garmin: Uploading activities to Garmin...
2021-01-07 08:25:49,519 [CRITICAL] Login Failure: Authentification failed.
Traceback (most recent call last):
  File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 95, in <module>
    PelotonToGarmin.run(config)
  File "/Users/awLibrary/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 82, in run
    raise e
  File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 79, in run
    garminUploader.uploadToGarmin(garminUploadHistoryTable)
  File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/lib/garminClient.py", line 29, in uploadToGarmin
    assert self.user.authenticate(), "Failed to authenticate garmin user."
AssertionError: Failed to authenticate garmin user.

**Comment by mhjansen79** [comment]
@Octopusprime83 any chance you could update the docker image on docker hub with this fix? Or I'm more than happy to learn to do it and help you keep the docker image up to date in the future.

**Comment by gabeosx** [comment]
I still cannot get mine to upload. I preserved my config.ini and checked the password. Anyone know what to do? garmin-uploader is showing as 1.0.8.

**Comment by philosowaffle** [comment]
Seems we have atleast 2 people for which this is not working. It is working for me, is it working for anyone else?

**Comment by Carbja23** [comment]
Working fine for me. Used new version with previous config.

**Comment by akramer115** [comment]
> The uploader version is showing as 1.0.8. I did preserve my old config.ini file and manually checked that the password saved there has no issues with logging into the Garmin site. I also gave it the old cross your fingers and reboot, but no luck.
> 
> 2021-01-07 08:25:48,520 - INFO - peloton-to-garmin: Uploading activities to Garmin...
> 2021-01-07 08:25:49,519 [CRITICAL] Login Failure: Authentification failed.
> Traceback (most recent call last):
> File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 95, in
> PelotonToGarmin.run(config)
> File "/Users/awLibrary/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 82, in run
> raise e
> File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/peloton-to-garmin.py", line 79, in run
> garminUploader.uploadToGarmin(garminUploadHistoryTable)
> File "/Users/aw/Library/Mobile Documents/com~apple~CloudDocs/Training/peloton-to-garmin-master/lib/garminClient.py", line 29, in uploadToGarmin
> assert self.user.authenticate(), "Failed to authenticate garmin user."
> AssertionError: Failed to authenticate garmin user.

This is my error too. I am using the new config file. Not sure if any of this is helpful, but I am using pip version 20.2.4, Python 3.9

**Comment by amy26point2** [comment]
I tried reinstalling python tonight and upgraded pip from 20.2.3 to 20.3.3, but it still threw the failed to authenticate garmin user error.

**Comment by philosowaffle** [comment]
Alright, new thing to try.  Let's see if you still get the authentication error when you use garmin-uploader directly.

https://github.com/La0/garmin-uploader#examples

If you still get an authentication error then I think we need to open a new issue on the garmin-uploader project so that La0 can investigate.

**Comment by akramer115** [comment]
@philosowaffle tried the garmin uploader directly and still getting auth issues. Triple checked creds too.

```
2021-01-10 11:31:24,590 [INFO] Try to login on GarminConnect...
2021-01-10 11:31:26,945 [CRITICAL] Login Failure: Login check failed.
Error: Invalid credentials
```

**Comment by philosowaffle** [comment]
Thanks for testing that out. At this point, I would recommend one of y'all experiencing the login issue open a fresh ticket on the garmin-upload project.  Hopefully, the owner will have some more insight on what may be going on.

**Comment by akramer115** [comment]
Just submitted [here](https://github.com/La0/garmin-uploader/issues/22).


@amy26point2 if you still have issues with the authentication too, please feel free to add to my ticket

**Comment by gabeosx** [comment]
Mine started working today for no apparent reason

**Comment by amy26point2** [comment]
Thank you. I did update to the ticket.
